### ISSUE TITLE
GLIBC_2.14 not found on CentOS 6

### ISSUE THREAD

**Issue by cseufert** [MayhemYDG/iltorb#35]
Hi,

I just updated iltorb to the latest version, and now i cant install it on my CentOS 6 box.

`
Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/secondchildhood/moddengine/node_modules/iltorb/build/bindings/encode.node)
`

Can you make it compile packages if the GLIBC is older than what you compiled against?

**Comment by MayhemYDG** [comment]
I'd suggest looking into this thread: https://github.com/JCMais/node-libcurl/issues/45

**Comment by oohnoitz** [comment]
We might be able to resolve this with: http://rjp.io/2012/04/09/fun-with-shared-libraries-version-glibc_2-14-not-found/. (It's a bit hard to read due to some bad formatting.)

TLDR; We would need to include a file in our compile process that overrides `memcpy` and points it to a specific `glibc` version since there were some breaking changes introduced between the "minor" version changes. This seems to be done in other native node libraries, but I'm not sure if this would be the best approach for us or a good idea since we pull in `brotli` as a dependency.

**Comment by MayhemYDG** [comment]
@cseufert is this still an issue on your side?

**Comment by cseufert** [comment]
But the problem actually seems to be that the binary you are distributing
is linked against a newer glibc. If I compile the package from src, like
the old version did,  it works fine.

**Comment by oohnoitz** [comment]
I might have a possible workaround for this. Tests are passing, but would like to have some additional confirmation before we go ahead and publish a new version with this change. Could you try and see if you are having any issues with the either of the following binaries @cseufert? I generated binaries for v4 (46), v6 (48), and v8 (57) since I wasn't sure what you'd be running on. The binaries should drop right into `build/bindings`.

- [iltorb-binaries-46.zip](https://github.com/MayhemYDG/iltorb/files/1114142/iltorb-binaries-46.zip)
- [iltorb-binaries-48.zip](https://github.com/MayhemYDG/iltorb/files/1114135/iltorb-binaries-48.zip)
- [iltorb-binaries-57.zip](https://github.com/MayhemYDG/iltorb/files/1114128/iltorb-binaries-57.zip)

**Comment by oohnoitz** [comment]
@cseufert this should be fixed in `1.3.2`.

**Comment by jimmyhchan** [comment]
This seems to have broken again in 1.3.4 and 1.3.5.  See #44

**Comment by GreenReaper** [comment]
FWIW this will likely break on [x32 ABI](https://en.wikipedia.org/wiki/X32_ABI) because it wasn't built until glibc 2.16 (in 2012), so its memcpy doesn't have symbols from 2.2.5 (in 2002). Adding a guard:
```
#if defined(__x86_64__) && !defined(__ILP32__) && defined(__GNU_LIBRARY__)
...
#endif
```
might be a good idea.
