### ISSUE TITLE
Unable to install ilotrb@1.3.5 due to firewall

### ISSUE THREAD

**Issue by yamarane** [MayhemYDG/iltorb#42]
I am trying to install node-saas which has ilotrb@1.3.5 as sub-dependency but ilotrb is depends on binaries which hosted on github. 

Due to firewall we are unable to download that binaries. Do we have any workaround for this?
(or)
Is there a way to override this host with different host?
https://github.com/MayhemYDG/iltorb/blob/6299dd80bcc13861eb398871808e290abcb320ba/package.json#L60

**Comment by oohnoitz** [comment]
Yes, there are a couple of things:

1) By *default*, if it is unable to download the pre-compiled binaries, it will fallback to compiling the binaries locally. This will require you to have the build tools required installed on your machine.

2) It is possible to override the host on v1.3.5+ using the following methods, since that release was when we first fixed the module name. I'll add this to the README later.

    a) with an ENV variable (could be stored in the local .npmrc file as well)

    `npm_config_iltorb_binary_host_mirror=https://... npm install iltorb`

    b) with an additional argument

    `npm install iltorb --iltorb_binary_host_mirror=https://...`

    Note: You would still need to take care of syncing the binaries yourself and make sure that the requests are valid. For example, setting the mirror link to `https://mirror.com/iltorb/`, you would need to create a subdirectory of the `version` with all of the binaries stored in there.
