### ISSUE TITLE
NPM package is published with all dependencies in node_modules

### ISSUE THREAD

**Issue by monshi** [MayhemYDG/iltorb#43]
Hello,
I noticed the published tarballs in NPM registry are way larger compared to version 1.2.1
https://registry.npmjs.org/iltorb/-/iltorb-1.2.1.tgz (496 KB)
https://registry.npmjs.org/iltorb/-/iltorb-1.3.5.tgz (2 MB)
Looks like node_module contains all direct and transitive dependencies, is it intentional?

**Comment by oohnoitz** [comment]
Yes, this is intentional.

With `1.0.13` and earlier versions, users were required to handle the entire compilation process locally. This changed with `1.1.0` when we started to provide compiled binaries via S3/GitHub. What you are seeing is the dependencies that get bundled via the `bundledDependencies` config in our `package.json` file, in this case everything needed for `node-pre-gyp` to work since this handles the install/fallback-to-build logic.
