### ISSUE TITLE
GLIBC_2.14 issue in 1.3.4 and 1.3.5 on RHEL6

### ISSUE THREAD

**Issue by jimmyhchan** [MayhemYDG/iltorb#44]
The prebuilt binaries for 1.3.4 and 1.3.5 is showing the GLIBC 2.14 error as seen in #35 

1.3.2 and 1.3.3 seems to work just fine. 
might be related to c2551eccd7b695a1587aec699f513e33f814239f

with RHEL6 with GLIBC at 2.12
`npm install iltorb@1.3.4 && node -e 'require("iltorb")'`  fails
whereas
`npm install iltorb@1.3.3 && node -e 'require("iltorb")'`  works

**Comment by jimmyhchan** [comment]
Odd thing is the building from source seems to work.

**Comment by oohnoitz** [comment]
My current suggestion would be to pin `iltorb` to `1.3.3` for now. There wasn't much changes in the following minor versions besides trying to add in support for Alpine Linux which uses musl libc (causing this issue to occur again) and moving the binaries to GitHub. This will take a bit of time to investigate though and come up with a better solution than these guards/hacks.

**Comment by oohnoitz** [comment]
@jimmyhchan This should be resolved in `v1.3.10`.

The only downside with our newest solution is that since we are still building against a newer version of GLIBC and no longer using the previous hack/workaround, Centos6/RHEL6 would need to have the necessary build tools installed (C+11 compiler) to compile. The current install process from `npm` goes like this for Centos6/RHEL6:

- download binaries 
- test downloaded binaries which will return the `GLIBC_2.14 not found` error
- compile against system `GLIBC` version
