### ISSUE TITLE
Cannot access the version prebuilded iltorbs

### ISSUE THREAD

**Issue by gemelgb** [MayhemYDG/iltorb#91]
Hi,

is there a posssibility to add an extra option in the package.json to enforce the build and installation of iltorb. Something like that?

"install-force-build": "node-gyp rebuild", 

The problem that I have is that my nexus build cannot access the prebuilded url (https://github.com/MayhemYDG/iltorb/releases/download/v2.4.3/iltorb-v2.4.3-node-v64-linux-x64.tar.gz). And unfortunetaly we cannot adjust the installation with the existing options --build-from-source because is a central build affecting hundreds of other apps..

Would be greatly appreciated if you could provide me a feedback!

Best Regards
Georgios

**Comment by oohnoitz** [comment]
I'm not exactly sure what the problem is without seeing the error output. We do have some instructions/suggestions on what to do when access to the binaries are blocked for some reason: https://github.com/MayhemYDG/iltorb#troubleshooting. Otherwise, it should be building from source if it is unable to download the binaries.

**Comment by gemelgb** [comment]
thanks, i think i got another solution to do that

Best Regards
Georgios
